config/routes.rb
Persona2::Application.routes.draw do
  resources :people

  root 'people#index'

  resources :people do
       resources :stories
  end

  resources :stories

  

end

app/models/person.rb
# coding: utf-8
class Person < ActiveRecord::Base
	
	has_many :stories, dependent: :destroy

	validates :name, presence: true
	validates :birth, presence: true

	after_create :build_default_stories

	before_save do
		self.description = self.description.gsub("\\", "")
		self.description = self.description.gsub("\r\n", "\\r\\n")
	end

	def get_dates_with_signs
		date_arr = []
		i = 0
		while i < stories.count() do
			if stories[i].date != nil
				date_arr << [stories[i].date.to_datetime.to_i, stories[i].story_type, stories[i].description]
			else
				date_arr << [0, stories[i].story_type, stories[i].description]
			end
			i += 1
		end
		date_arr.sort! { |x, y| x[0] <=> y[0]}
		return date_arr.to_json
	end	

	def get_dates_count
		return stories.count()
	end	


	def get_birth
        return birth.to_datetime.to_i
	end

	def get_data_for_graph2
		stories_counter = stories.count()
		if (stories_counter) <1 then
			return "число событий <1, не могу построить график"
		end	
		stories_text = ""
		stories.each do |story|
			stories_text+=story.date.to_s + ", "
		end	
	return stories_text
	end	

	def get_person_names
		person_arr = []
		all_persons = Person.all

		i = 0
		while i < all_persons.count() do
			person_arr << [all_persons[i].id, all_persons[i].name]
			i += 1
		end

		return person_arr.to_json
		
	end

	private
		def build_default_stories
		  # build default profile instance. Will use default params.
		  # The foreign key to the owning User model is set automatically
		  self.stories.create(:description => 'Любовь 1', :story_type => 1)
		  self.stories.create(:description => 'Любовь 2', :story_type => 1)
		  self.stories.create(:description => 'Любовь 3', :story_type => 1)
		  self.stories.create(:description => 'Выигрыш', :story_type => 1)
		  self.stories.create(:description => 'Рождение детей', :story_type => 1)
		  self.stories.create(:description => 'Свадьба', :story_type => 1)

		  self.stories.create(:description => 'Расставание 1', :story_type => 0)
		  self.stories.create(:description => 'Расставание 2', :story_type => 0)
		  self.stories.create(:description => 'Расставание 3', :story_type => 0)
		  self.stories.create(:description => 'Предательство', :story_type => 0)
		  self.stories.create(:description => 'Финансовые потери', :story_type => 0)
		  self.stories.create(:description => 'Смерть близкого', :story_type => 0)
		  self.stories.create(:description => 'Болезнь, травма, авария', :story_type => 0)
		  true 
		end

end

app/models/point.rb
class Point < ActiveRecord::Base
	belongs_to :story, dependent: :destroy
end

app/models/story.rb
# coding: utf-8
class Story < ActiveRecord::Base
	belongs_to :person

    POSITIVE = 1
    NEGATIVE = 0
    ALL_TYPES = [POSITIVE, NEGATIVE]
    def getStoryType
    	sType = ""
    	if story_type == 0 then
			sType = "Негативная"
		else 
			sType = "Позитивная"
		end	
		return sType
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  http_basic_authenticate_with name: "skala", password: "skala"
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @people = Person.all
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.create(person_params)

    respond_to do |format|
      if @person.errors.empty?
        format.html { redirect_to people_path, notice: 'Person was successfully created.' }
      else
        format.html { redirect_to people_path, notice: 'Error.' }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to people_path, notice: 'Person was successfully updated.' }
      else
        format.html { redirect_to people_path, notice: 'Error.' }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :birth, :psycho, :extrasensitive, :description)
    end
    
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	def create
		@person = Person.find(params[:person_id])
		@story = @person.stories.create(params[:story].permit(:date, :story_type, :description))
		redirect_to person_path(@person)
	end

	def destroy
		Story.destroy(params[:id])
		@person = Person.find(params[:person_id])
		redirect_to person_path(@person)
	end

	def update
		@person = Person.find(params[:person_id])
		@story = Story.where(id: params[:id]).first
		@story.update(story_params)
		redirect_to people_path
	end

	private
    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:date, :story_type, :description, :person_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Персона</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>				
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="hero-unit">

  <div class="field">
    Имя <br>
    <%= f.text_field :name %><br>
    Дата рождения <br>
    <%= f.date_field :birth %><br>
  </div>
  <div class="actions">
   <%= f.submit :class => "btn btn-large btn-success", :value => "Сохранить" %> 
  </div>
</div>


<% end %>

app/views/people/edit.html.erb
<%= link_to 'К персонам', people_path %>
<br/>

<h1>Редактирование персоны</h1>

<%= render 'form' %>

app/views/people/index.html.erb
<div class="divDemoBody">
    <div id="windowTitleDialog" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="windowTitleLabel" aria-hidden="true">
        <div class="modal-header">
            <a href="#" class="close" data-dismiss="modal">&times;</a>
            <h3>Создание новой персоны</h3>
        </div>
        <%= form_for(Person.new) do |f| %>
        <div class="modal-body">
            <div class="divDialogElements">
                <div id = "newPersonForm">
                    <div class="hero-unit" style="font-size:14px; padding-top: 10px; padding-bottom: 10px; background-color: white; text-align: center;">
                        <b>Имя:</b><br>
                        <%= f.text_field :name %><br>
                        <b>Дата рождения:</b><br>
                        <%= f.date_field :birth %><br>
                        <b>Примечание:</b><br>
                        <%= f.text_area(:description, :size => "50x5") %><br>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a data-target="#" class="btn" onclick="closeDialog ('windowTitleDialog');">Отмена</a>
            <%= f.submit :class => "btn", :value => "Создать" %>
            </div>
        </div>
        <% end %>
    </div>

<div class="container" style="padding-top: 10px; padding-bottom: 30px; width: 98%;">

    <table id="navigationTable" class="table table-condensed" style="width: 100%;">

        <tr>
            <td style="width: 50%;">
                <div class="left">
                    <select name="firstPersons" id="firstPersons" onchange="plotAccordingToChoicesChangePerson(0, false)">
                    </select>
                </div>
                <div id = "firstName" class="right">
                </div>
            </td>
            <td style="width: 50%;">
                <div class="left">
                    <select name="otherPersons" id="otherPersons" onchange="plotAccordingToChoicesChangePerson(1, false)">
                    </select>
                </div>
                <div id = "secondName" class="right">
                </div>
            </td>
        </tr>

        <tr>
            <td style="width: 50%;">
                <div id = "firstDescription" class="text-left">
                        
                </div> 
            </td>
            <td style="width: 50%;">
                <div id = "secondDescription" class="text-left">
                        
                </div> 
            </td>
        </tr>

        <tr>
            <td>
                <div id="firstDates" align="center"></div>
            </td>
            <td>
                <div id="secondDates" align="center"></div>
            </td>
        </tr>

        <tr>
            <td>
                <div id="firstCustomDate" align="center"></div>
            </td>
            <td>
                <div id="secondCustomDate" align="center"></div>
            </td>
        </tr>

    </table>
    
    <div class="accordion" id="accordion5">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion5" href="#collapseFour">
            Выбор графиков
          </a>
        </div>
        <div id="collapseFour" class="accordion-body collapse">
          <div class="accordion-inner">
            <table id="navigationTable" class="table table-condensed" style="width: 100%;">

                <tr>
                    <td>
                        <div id='choicestable' align="center"></div>
                    </td>
                    <td>
                        <div id='choicestableotherperson' align="center"></div>
                    </td>
                </tr>

            </table>
          </div>
        </div>
      </div>
    </div>

<%= render "graph2"%>
</div>

<script type="text/javascript">

  function closeDialog (name) 
  {
      $('#' + name).modal('hide'); 
  };
  function okClicked (name) 
  {
      closeDialog (name);
  };


</script>

app/views/people/new.html.erb
<h1>Новая персона</h1>

<%= render 'form' %>

<%= link_to 'Назад', people_path %>

app/views/people/show.html.erb
<%= link_to 'На главную', people_path %> | 
<%= link_to 'Редактировать', edit_person_path(@person) %>
<br>

<p id="notice"><%= notice %></p>

<div class="hero-unit" style="padding-top: 10px; padding-bottom: 0px;">

    <table id="navigationTable" class="table table-bordered table-condensed" style="width: 100%;">

        <tr>
            <td style="text-align: center; font-size:20px; padding:10px; vertical-align: top; width: 50%;">
                <b>Имя: <%= @person.name %></b>
            </td>
            <td style="text-align: center; font-size:20px; padding:10px; vertical-align: top; width: 50%;">
                <b>Вторая персона:</b>
                <select name="otherPersons" id="otherPersons" onchange="plotAccordingToChoicesChangePerson()">
                </select>
            </td>
        </tr>

        <tr>
            <td style="text-align: center; font-size:14px; padding:10px; vertical-align: top; width: 50%;">
                <b>Дата рождения: <%= @person.birth.strftime("%d.%m.%Y") %></b>
            </td>
            <td style="text-align: center; font-size:14px; padding:10px; vertical-align: top; width: 50%;">
                <div id="secondBirth" align="center"></div>
            </td>
        </tr>

        <tr>
            <td style="text-align: center; left; font-size:12px; padding:10px; vertical-align: top;">

                <table class="table table-bordered table-condensed">
                <tr>
                  <th>Дата</th>
                  <th>Значение</th>
                  <th>Описание</th>
                  <th>Действие</th>
                </tr> 
                <tbody>
                <% for i in 0..@person.get_dates_count - 1 %>
                <tr>
                    <%= render @person.stories[i] %>
                </tr>
                <%end%>
                <tr>
                    <%=form_for([@person, @person.stories.build]) do |f| %>
                    <td>
                        <%= f.date_field :date, :class=>"input-medium" %>
                    </td>
                    <td>
                        <%= f.select(:story_type, [["Позитивная", Story::POSITIVE], ["Негативная", Story::NEGATIVE]], {}, {:class=>"input-medium"}) %>
                    </td>
                    <td>
                        <%= f.text_field :description, :class=>"input-small" %>
                    </td>
                    <td>
                        <%= f.submit :class => "btn btn-primary btn-link btn-small", :value => "Создать" %>
                    </td>
                    <% end %>
                </tr>
                </tbody>
                </table>
                
            </td>
            <td style="padding:10px; font-size:12px; vertical-align: top;">
                <div id="secondDates" align="center"></div>
            </td>
        </tr>

        <tr>
            <td style="padding:10px; font-size:12px; vertical-align: top; text-align: center; width: 50%;">
                <div id='choicestable' align="center"></div>
            </td>
            <td style="padding:10px; font-size:12px; vertical-align: top; text-align: center; width: 50%;">
                <div id='choicestableotherperson' align="center"></div>
            </td>
        </tr>

    </table>

<% if @person.valide_dates_for_graph  %>
<%= render "graph1"%>
<% end %>
<br>
</div>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <div class="actions">
    <%= f.submit %>
  </div>  
<% end %>

app/views/stories/_story.html.erb
<%= form_for([story.person, story]) do |f| %>

<th>
	<div id = "dateShow<%= story.date.strftime('%d.%m.%Y') %>" style="display: block;" >
	<%= story.date.strftime('%d.%m.%Y') %>
	</div>
	<div id = "date<%= story.date.strftime('%d.%m.%Y') %>" style="display: none;" >
    <%= f.date_field :date, :class=>"input-medium" %>
	</div>
</th> 
<th>
	<div id = "typeShow<%= story.date.strftime('%d.%m.%Y') %>" style="display: block;" >
	<%= story.getStoryType%>
	</div>
	<div id = "type<%= story.date.strftime('%d.%m.%Y') %>" style="display: none;" >
    <%= f.select(:story_type, [["Позитивная", Story::POSITIVE], ["Негативная", Story::NEGATIVE]], {}, {:class=>"input-medium"}) %>
	</div>
</th>
<th>
	<div id = "descShow<%= story.date.strftime('%d.%m.%Y') %>" style="display: block;" >
	<%= story.description%> 
	</div>
	<div id = "desc<%= story.date.strftime('%d.%m.%Y') %>" style="display: none;" >
	<%= f.text_field :description, :class=>"input-small" %>
	</div>
</th>
<td>
    <table>
        <tr>
        <td>
	        <p id = "edit<%= story.date.strftime('%d.%m.%Y') %>" class="btn btn-primary btn-link btn-small" onclick="showDiv('<%= story.date.strftime('%d.%m.%Y') %>');">
	        	 Редактировать
	        </p>
	        <div id = "save<%= story.date.strftime('%d.%m.%Y') %>" style="display: none;" >
	        <%= f.submit :class => "btn btn-primary btn-link btn-small", :value => "Сохранить" %>
	    	</div>
        </td>
        <% end %>
        <td>
        	<%= link_to 'Удалить', [story.person, story], method: :delete, data: {confirm:'Вы уверены? '}, :class => "btn btn-primary btn-link btn-small" %>
        </td>
        </tr>
    </table>
</td>

<script type="text/javascript">
function showDiv(elemId)
{
	document.getElementById("date" + elemId).style.display = 'block';
	document.getElementById("type" + elemId).style.display = 'block';
	document.getElementById("save" + elemId).style.display = 'block';
	document.getElementById("desc" + elemId).style.display = 'block';
	document.getElementById("edit" + elemId).style.display = 'none';

	document.getElementById("dateShow" + elemId).style.display = 'none';
	document.getElementById("typeShow" + elemId).style.display = 'none';
	document.getElementById("descShow" + elemId).style.display = 'none';
}
</script>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @stories.each do |story| %>
      <tr>

        <td><%= link_to 'Показать', story %> </td>
        <td><%= link_to 'Редактировать', edit_story_path(story) %> </td>
        <td><%= link_to 'Удалить', story, method: :delete, data: { confirm: 'Вы уверены?' } %> </td>
      </tr>
    <% end %>

  </thead>

  <tbody>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_person_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>События</strong>

</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>